// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pi_Plant.Data;

#nullable disable

namespace Pi_Plant.Migrations
{
    [DbContext(typeof(PlantMonitoringContext))]
    partial class PlantMonitoringContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Pi_Plant.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IdealMaxHumidity")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMaxSoilMoisture")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMaxSunLight")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMaxTemperature")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMinHumidity")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMinSoilMoisture")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMinSunLight")
                        .HasColumnType("REAL");

                    b.Property<double>("IdealMinTemperature")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NickName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PlantedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdealMaxHumidity = 60.0,
                            IdealMaxSoilMoisture = 70.0,
                            IdealMaxSunLight = 100.0,
                            IdealMaxTemperature = 28.0,
                            IdealMinHumidity = 40.0,
                            IdealMinSoilMoisture = 40.0,
                            IdealMinSunLight = 1.0,
                            IdealMinTemperature = 20.0,
                            IsActive = true,
                            Location = "Office Shelf",
                            Name = "Turtle Plant",
                            NickName = "",
                            PlantedDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Species = "???"
                        });
                });

            modelBuilder.Entity("Pi_Plant.Models.SensorReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("REAL");

                    b.Property<double>("LightLevel")
                        .HasColumnType("REAL");

                    b.Property<int>("PlantId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SoilMoisture")
                        .HasColumnType("REAL");

                    b.Property<double>("Temperature")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("PlantId", "Timestamp");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("Pi_Plant.Models.SensorReading", b =>
                {
                    b.HasOne("Pi_Plant.Models.Plant", "Plant")
                        .WithMany("SensorReadings")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("Pi_Plant.Models.Plant", b =>
                {
                    b.Navigation("SensorReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
